# Generated by Django 3.2.3 on 2021-05-30 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarafas',
            new_name='Tarefas',
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['-data_de_criacao'], 'verbose_name_plural': 'Tarefa'},
        ),
    ]
